-- create table state(
-- stateid int PRIMARY key ,
-- statename varchar(10) unique not NULL
-- );
-- create table place(
-- placeid int PRIMARY key ,
-- placename varchar(10) unique not NULL,
-- placedesc varchar(10) not NULL,
-- placeimg varchar(10) not NULL,
-- placeloc varchar(10)  not NULL,
-- hours int unique not NULL,
-- budget int  not NULL
-- );
-- create table city(
-- cityid int PRIMARY key ,
-- cityname varchar(10) unique not NULL
-- );
-- create table state_city(
-- cityid int ,
-- stateid int,
-- foreign key (cityid) references city (cityid) on delete CASCADE,
-- foreign key (stateid) references state (stateid) on delete CASCADE
-- );
-- create table city_place(
-- cityid int ,
-- placeid int,
-- foreign key (cityid) references city (cityid) on delete CASCADE,
-- foreign key (placeid) references place (placeid) on delete CASCADE
-- );
-- insert into state values(1,'Karnataka');
-- insert into place values(2,'Jamboti Hills','The longest river in Goa, the Mandovi, originates in Jamboti Hills, which is a picturesque and tranquil location to explore.','https://www.google.com/imgres?q=jamboti%20hills&imgurl=https%3A%2F%2Fmonomousumi.com%2Fwp-content%2Fuploads%2Fjamboti.jpg&imgrefurl=https%3A%2F%2Fmonomousumi.com%2Fjamboti%2F&docid=4jzBnTt5esJjGM&tbnid=FqYjxADJ28bvbM&vet=12ahUKEwjarKixsbOIAxVs7zgGHa9BKFQQM3oECFQQAA..i&w=1600&h=1066&hcb=2&ved=2ahUKEwjarKixsbOIAxVs7zgGHa9BKFQQM3oECFQQAA','15.682620546738592, 74.34520858329472',3,99);
-- insert into state_city values(1,1);
-- insert into city values(1,'Belagavi');
-- insert into city_place values(1,1);
-- alter table city
-- add citydesc varchar(10);
-- update place
-- set placeimg='jamboti.jpg'
-- where placeid=2;
-- create table added(
-- placeid integer primary key AUTOINCREMENT,
-- placename varchar(30),
-- placeloc varchar(40),
-- budget int,
-- hours int,
-- foreign key (placeid) references place (placeid) on delete CASCADE,
-- foreign key (placename) references place (placename) on delete CASCADE,
-- foreign key (placeloc) references place (placeloc) on delete CASCADE,
-- foreign key (budget) references place (budget) on delete CASCADE,
-- foreign key (hours) references place (hours) on delete CASCADE
-- );
-- DELETE FROM added
-- WHERE placeid =6;


